version: '3.5'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es
    environment:
      - node.name=es
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
  gra:
    image: grafana/grafana
    container_name: gra
    ports:
      - 3000:3000